export const segmentFields: Record<string, string[]> = {
    'MSH': [
        'Field Separator', 
        'Encoding Characters', 
        'Sending Application', 
        'Sending Facility', 
        'Receiving Application', 
        'Receiving Facility', 
        'Date/Time Of Message', 
        'Security', 
        'Message Type', 
        'Message Control ID', 
        'Processing ID', 
        'Version ID', 
        'Sequence Number', 
        'Continuation Pointer', 
        'Accept Acknowledgment Type', 
        'Application Acknowledgment Type', 
        'Country Code', 
        'Character Set', 
        'Principal Language Of Message', 
        'Alternate Character Set Handling Scheme', 
        'Message Profile Identifier', 
        'Sending Responsible Organization', 
        'Receiving Responsible Organization', 
        'Sending Network Address', 
        'Receiving Network Address'
        ],
    'EVN':
      ['Event Type Code', 'Recorded Date/Time', 'Date/Time Planned Event', 'Event Reason Code', 'Operator ID', 'Event Occurred', 'Event Facility'],
    'OBR': [
        'Set ID - OBR',
        'Placer Order Number',
        'Filler Order Number',
        'Universal Service Identifier',
        'Priority - OBR',
        'Requested Date/Time',
        'Observation Date/Time',
        'Observation End Date/Time',
        'Collection Volume',
        'Collector Identifier',
        'Specimen Action Code',
        'Danger Code',
        'Relevant Clinical Information',
        'Specimen Received Date/Time',
        'Specimen Source',
        'Ordering Provider',
        'Order Callback Phone Number',
        'Placer Field 1',
        'Placer Field 2',
        'Filler Field 1',
        'Filler Field 2',
        'Results Rpt/Status Chng - Date/Time',
        'Charge to Practice',
        'Diagnostic Serv Sect ID',
        'Result Status',
        'Parent Result',
        'Quantity/Timing',
        'Result Copies To',
        'Parent',
        'Transportation Mode',
        'Reason for Study',
        'Principal Result Interpreter',
        'Assistant Result Interpreter',
        'Technician',
        'Transcriptionist',
        'Scheduled Date/Time',
        'Number of Sample Containers',
        'Transport Logistics of Collected Sample',
        'Collector\'s Comment',
        'Transport Arrangement Responsibility',
        'Transport Arranged',
        'Escort Required',
        'Planned Patient Transport Comment',
        'Procedure Code',
        'Procedure Code Modifier',
        'Placer Supplemental Service Information',
        'Filler Supplemental Service Information',
        'Medically Necessary Duplicate Procedure Reason',
        'Result Handling'
        ],
    'OBX': [
        'Set ID - OBX',
        'Value Type',
        'Observation Identifier',
        'Observation Sub-ID',
        'Observation Value',
        'Units',
        'References Range',
        'Abnormal Flags',
        'Probability',
        'Nature of Abnormal Test',
        'Observation Result Status',
        'Effective Date of Reference Range',
        'User Defined Access Checks',
        'Date/Time of the Observation',
        'Producer\'s ID',
        'Responsible Observer',
        'Observation Method',
        'Equipment Instance Identifier',
        'Date/Time of the Analysis'
        ],
    'ORC': [
        'Order Control',
        'Placer Order Number',
        'Filler Order Number',
        'Placer Group Number',
        'Order Status',
        'Response Flag',
        'Quantity/Timing',
        'Parent Order',
        'Date/Time of Transaction',
        'Entered By',
        'Verified By',
        'Ordering Provider',
        'Enterer\'s Location',
        'Call Back Phone Number',
        'Order Effective Date/Time',
        'Order Control Code Reason',
        'Entering Organization',
        'Entering Device',
        'Action By',
        'Advanced Beneficiary Notice Code',
        'Ordering Facility Name',
        'Ordering Facility Address',
        'Ordering Facility Phone Number',
        'Ordering Provider Address',
        'Order Status Modifier',
        'Advanced Beneficiary Notice Override Reason',
        'Filler\'s Expected Availability Date/Time',
        'Confidentiality Code',
        'Order Type',
        'Enterer Authorization Mode'
        ],
    'PID': [
        'Set ID – PID', 
        'Patient ID', 
        'Patient Identifier List', 
        'Alternate Patient ID – PID', 
        'Patient Name', 
        'Mother\'s Maiden Name',
        'Date/Time Of Birth', 
        'Administrative Sex', 
        'Patient Alias', 
        'Race',
        'Patient Address', 
        'County Code', 
        'Phone Number – Home', 
        'Phone Number – Business', 
        'Primary Language', 
        'Marital Status', 
        'Religion',
        'Patient Account Number', 
        'SSN Number – Patient', 
        'Driver\'s License Number – Patient',
        'Mother\'s Identifier', 
        'Ethnic Group', 
        'Birth Place', 
        'Multiple Birth Indicator', 
        'Birth Order', 
        'Citizenship', 
        'Veterans Military Status',
        'Nationality', 
        'Patient Death Date And Time', 
        'Patient Death Indicator',
        'Identity Unknown Indicator', 
        'Identity Reliability Code', 
        'Last Update Date/Time', 
        'Last Update Facility',
        'Taxonomic Classification Code', 
        'Breed Code', 
        'Strain', 
        'Production Class Code', 
        'Tribal Citizenship', 
        'Patient Telecommunication Information'
        ],
    'PV1': [
        'Set ID – PV1',
        'Patient Class',
        'Assigned Patient Location',
        'Admission Type',
        'Preadmit Number',
        'Prior Patient Location',
        'Attending Doctor',
        'Referring Doctor',
        'Consulting Doctor',
        'Hospital Service',
        'Temporary Location',
        'Preadmit Test Indicator',
        'Re-admission Indicator',
        'Admit Source',
        'Ambulatory Status',
        'VIP Indicator',
        'Admitting Doctor',
        'Patient Type',
        'Visit Number',
        'Financial Class',
        'Charge Price Indicator',
        'Courtesy Code',
        'Credit Rating',
        'Contract Code',
        'Contract Effective Date',
        'Contract Amount',
        'Contract Period',
        'Interest Code',
        'Transfer to Bad Debt Code',
        'Transfer to Bad Debt Date',
        'Bad Debt Agency Code',
        'Bad Debt Transfer Amount',
        'Bad Debt Recovery Amount',
        'Delete Account Indicator',
        'Delete Account Date',
        'Discharge Disposition',
        'Discharged to Location',
        'Diet Type',
        'Servicing Facility',
        'Bed Status',
        'Account Status',
        'Pending Location',
        'Prior Temporary Location',
        'Admit Date/Time',
        'Discharge Date/Time',
        'Current Patient Balance',
        'Total Charges',
        'Total Adjustments',
        'Total Payments',
        'Alternate Visit ID',
        'Visit Indicator',
        'Other Healthcare Provider',
        'Service Episode Description',
        'Service Episode Identifier'
        ],
    'PV2':
      ['Prior Pending Location', 'Accommodation Code', 'Admit Reason', 'Transfer Reason', 'Patient Valuables', 'Patient Valuables Location', 'Visit User Code',
      'Expected Admit Date', 'Expected Discharge Date', 'Estimated Length of Inpatient Stay', 'Actual Length of Inpatient Stay', 'Visit Description', 'Referral Source Code',
      'Previous Service Date', 'Employment Illness Related Indicator', 'Purge Status Code', 'Purge Status Date', 'Special Program Code', 'Retention Indicator', 'Expected Number of Insurance Plans',
      'Visit Publicity Code', 'Visit Protection Indicator', 'Clinic Organization Name', 'Patient Status Code', 'Visit Priority Code', 'Previous Treatment Date', 'Expected Discharge Disposition',
      'Signature on File Date', 'First Similar Illness Date', 'Patient Charge Adjustment Code', 'Recurring Service Code', 'Billing Media Code', 'Expected Surgery Date & Time',
      'Military Partnership Code', 'Military Non-Availability Code', 'Newborn Baby Indicator', 'Baby Detained Indicator'],
    'DG1':
      ['Set ID - DG1', 'Diagnosis Coding Method', 'Diagnosis Code', 'Diagnosis Description', 'Diagnosis Date/Time', 'Diagnosis/DRG Type', 'Major Diagnostic Category',
      'Diagnostic Related Group', 'DRG Approval Indicator', 'DRG Grouper Review Code', 'Outlier Type', 'Outlier Days', 'Outlier Cost', 'Grouper Version and Type',
      'Diagnosis/DRG Priority', 'Diagnosing Clinician', 'Diagnosis Classification', 'Confidential Indicator', 'Attestation Date/Time'],
    'PR1':
      ['Set ID - PR1', 'Procedure Coding Method', 'Procedure Code', 'Procedure Description', 'Procedure Date/Time', 'Procedure Type', 'Procedure Minutes', 'Anesthesiologist',
      'Anesthesia Code', 'Anesthesia Minutes', 'Surgeon', 'Procedure Practitioner', 'Consent Code', 'Procedure Priority', 'Associated Diagnosis Code'],
    'PD1':
      ['Living Dependency', 'Living Arrangement', 'Patient Primary Facility', 'Patient Primary Care Provider Name & ID No.', 'Student Indicator', 'Handicap', 'Living Will',
      'Organ Donor', 'Separate Bill', 'Duplicate Patient', 'Publicity Indicator', 'Protection Indicator'],
    'AL1':
      ['Set ID - AL1', 'Allergen Type Code', 'Allergen Code/Mnemonic/Description', 'Allergy Severity Code', 'Allergy Reaction Code', 'Identification Date'],
    'MRG':
      ['Prior Patient ID - Internal', 'Prior Alternate Patient ID', 'Prior Patient Account Number', 'Prior Patient ID - External', 'Prior Visit Number', 'Prior Alternate Visit ID', 'Prior Patient Name'],
    'GT1':
      ['Set ID - GT1', 'Guarantor Number', 'Guarantor Name', 'Guarantor Spouse Name', 'Guarantor Address', 'Guarantor Ph Num- Home', 'Guarantor Ph Num-Business',
      'Guarantor Date/Time of Birth', 'Guarantor Sex', 'Guarantor Type', 'Guarantor Relationship', 'Guarantor SSN', 'Guarantor Date - Begin', 'Guarantor Date - End', 'Guarantor Priority',
      'Guarantor Employer Name', 'Guarantor Employer Address', 'Guarantor Employ Phone Number', 'Guarantor Employee ID Number', 'Guarantor Employment Status', 'Guarantor Organization',
      'Guarantor Billing Hold Flag', 'Guarantor Credit Rating Code', 'Guarantor Death Date And Time', 'Guarantor Death Flag', 'Guarantor Charge Adjustment Code', 'Guarantor Household Annual Income',
      'Guarantor Household Size', 'Guarantor Employer ID Number', 'Guarantor Marital Status Code', 'Guarantor Hire Effective Date', 'Employment Stop Date', 'Living Dependency', 'Ambulatory Status',
      'Citizenship', 'Primary Language', 'Living Arrangement', 'Publicity Indicator', 'Protection Indicator', 'Student Indicator', 'Religion', 'Mother\'s Maiden Name', 'Nationality', 'Ethnic Group',
      'Contact Person\'s Name', 'Contact Person\'s Telephone Number', 'Contact Reason', 'Contact Relationship Code', 'Job Title', 'Job Code/Class', 'Guarantor Employer\'s Organization Name', 'Handicap',
      'Job Status', 'Guarantor Financial Class', 'Guarantor Race'],
    'NTE':
      ['Set ID - NTE', 'Source of Comment', 'Comment', 'Comment Type'],
    'NK1':
      ['Set ID - NK1', 'Name', 'Relationship', 'Address', 'Phone Number', 'Business Phone Number', 'Contact Role', 'Start Date', 'End Date', 'Next of Kin / Associated Parties Job Title',
      'Next of Kin / Associated Parties Job Code/Class', 'Next of Kin / Associated Parties Employee Number', 'Organization Name', 'Marital Status', 'Sex', 'Date/Time of Birth'],
    'IN1':
      ['Set ID - IN1', 'Insurance Plan ID', 'Insurance Company ID', 'Insurance Company Name', 'Insurance Company Address', 'Insurance Co. Contact Person', 'Insurance Co Phone Number',
      'Group Number', 'Group Name', 'Insured\'s Group Emp ID', 'Insured\'s Group Emp Name', 'Plan Effective Date', 'Plan Expiration Date', 'Authorization Information', 'Plan Type',
      'Name Of Insured', 'Insured\'s Relationship To Patient', 'Insured\'s Date Of Birth', 'Insured’s Address', 'Assignment Of Benefits', 'Coordination Of Benefits', 'Coord Of Ben. Priority',
      'Notice Of Admission Flag', 'Notice Of Admission Date', 'Report Of Eligibility Flag', 'Report Of Eligibility Date', 'Release Information Code', 'Pre-Admit Cert (PAC)',
      'Verification Date/Time', 'Verification By', 'Type Of Agreement Code', 'Billing Status', 'Lifetime Reserve Days', 'Delay Before L.R. Day', 'Company Plan Code', 'Policy Number',
      'Policy Deductible', 'Policy Limit - Amount', 'Policy Limit - Days', 'Room Rate - Semi-Private', 'Room Rate - Private', 'Insured’s Employment Status', 'Insured\'s Sex',
      'Insured\'s Employer Address', 'Verification Status', 'Prior Insurance Plan ID', 'Coverage Type', 'Handicap', 'Insured’s ID Number']
  }